/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SAINTMARTI' at '14/12/16 16:44' with Gradle 3.2.1
 *
 * @author SAINTMARTI, @date 14/12/16 16:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
