import static org.junit.Assert.*;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'SAINTMARTI' at '14/12/16 16:44' with Gradle 3.2.1
 *
 * @author SAINTMARTI, @date 14/12/16 16:44
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
